/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github;

import org.junit.Test;
import static org.junit.Assert.*;

public class CodingInterviewPracticeTest {
    @Test public void appHasAGreeting() {
        CodingInterviewPractice classUnderTest = new CodingInterviewPractice();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
